export const CLEAR_ACTION = 'CLEAR_ACTION';

export const DATA_LOADING_STARTED = 'DATA_LOADING_STARTED';
export const DATA_LOADING_SUCCESS = 'DATA_LOADING_SUCCESS';
export const DATA_LOADING_ERROR = 'DATA_LOADING_ERROR';

